remote_theme: lightster/jekyll-theme-scrawl@v0.1.19

title: Quick Switcher

sass:
  sass_dir: .
  style: compressed

exclude:
  - build.js
  - changelog.md
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE*
  - Makefile
  - node_modules
  - package.json
  - README.md
  - vendor
  - yarn.lock


plugins:
  # force included by GitHub Pages
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  # required by {% seo %} tag
  - jekyll-seo-tag

permalink: pretty
